apiVersion: v1
kind: ConfigMap
metadata:
  name: lv10-s3-minio-demo
  namespace: default
data:
  APP_NAME: "S3 Demo"
  APP_ENV: local
  APP_DEBUG: "true"
  DB_CONNECTION: sqlite
  DB_DATABASE: database.sqlite
  FILESYSTEM_DISK: s3-files
  AWS_ACCESS_KEY_ID: access-key
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: lv10-s3-minio-demo
  AWS_USE_PATH_STYLE_ENDPOINT: "true"
  AWS_ENDPOINT: http://s3-host:9000
